<?php Session_Start(); if (!isset($_SESSION['validate'])) { require('../validator.php'); } ?>
<html>
<head>
  <script type="text/JavaScript" src="wplang.js">
 </script>
  <script type="text/JavaScript">
 
<!--
var WinProHelpAvailableLanguages=["ENG","FRA"];
var WinProHelpPageName=["Milling","Usinage"];
WPlangInit(WinProHelpAvailableLanguages);
//Redirect browser to frame page if page is not in the content frame.
if(top.frames.length==0) { top.location.href="index.php?usinage.php"; }
else { parent.quicksync('a2.5.8'); }
//--></script>
  <script type="text/javascript" src="highlight.js">
 </script>
  <title>Usinage</title>
  <meta name="keywords" content="Usinage">
  <meta http-equiv="Content-Type" content="text/php; charset=iso-8859-1">
  <meta http-equiv="Content-Style-Type" content="text/css">
  <link type="text/css" href="default.css" rel="stylesheet">
</head>

<body style="margin: 0px 0px 0px 0px; background: #FFFFFF;"
onload="AddTitleAndLangFlags();highlight();">

<div id="hmpopupDiv"
style="visibility:hidden; position:absolute; z-index:1000;">
</div>

<table width="100%" border="0" cellspacing="0" cellpadding="5"
bgcolor="#FF8000">
  <tbody>
    <tr valign="middle">
      <td align="left"><p class="p_Heading1"><span class="f_Heading1"
        style="font-size: 6pt; font-weight: normal;"> </span></p>

        <p class="p_Heading1"><span id="titlepage"
        class="f_Heading1"></span></p>
      </td>
      <td align="center">
        <div id="langflags">
        </div>
      </td>
      <td align="right"><span style="font-size: 9pt"><a
        href="introduction.php">Top</a>  <a
        href="remplacerpar.php">Previous</a>  <a href="vuecoupe.php">Next</a>
        </span> </td>
    </tr>
  </tbody>
</table>

<div class="ENG">
<!-- Placeholder for topic body. -->

<table width="100%" border="0" cellspacing="0" cellpadding="5">
  <tbody>
    <tr valign="top">
      <td align="left"><p> </p>

        <p>These instructions let you define milling instructions on the
        profiles of the window (module).</p>

        <p>Basically, WinPro lets you define your millings in a logical way,
        without thinking about the constraints of the milling centre. For
        example, if a milling is generated by a fitting, but must apply to the
        outer frame profiles (frame or transom), you only need to give its
        position relatively to the fitting. WinPro will adjust the position on
        the outer frame automatically, in every possible situation. You can
        also select from which origin the milling position is to be computed,
        ignoring the requirements of your milling centre.</p>

        <p>To better meet the milling requirements, WinPro has 2 milling
        instructions, each of which supporting several sets of parameters.</p>

        <p>These instructions always follow the same basic layout: you give,
        successively, the source of the milling position, its identification,
        and its destination.</p>

        <p style="background: #fffff2;"><span
        style="font-size: 5pt; color: #000000;"> </span></p>

        <p style="margin: 0px 0px 0px 24px;">The first instruction, <span
        class="f_Variables">Milling</span>, uses any of these syntax:</p>

        <p style="margin: 0px 0px 0px 48px;"><span class="f_Variables"
        style="font-weight: bold;">Milling (position, origin, type, code,
        frame, side[, leaf])</span></p>

        <p style="margin: 0px 0px 0px 48px;"><span class="f_Variables"
        style="font-weight: bold;">Milling (position, origin, type, code,
        SPECIAL, category, side[, leaf])</span></p>

        <p style="margin: 0px 0px 0px 48px;"><span class="f_Variables"
        style="font-weight: bold;">Milling (position, origin, type, code,
        AUTO)</span></p>

        <p class="p_Interligne"><span class="f_Interligne"
        style="font-weight: bold;"> </span></p>

        <p style="margin: 0px 0px 0px 24px;">The second instruction, <span
        class="f_Variables">MultMilling</span>, uses any of these syntax:</p>

        <p style="margin: 0px 0px 0px 48px;"><span class="f_Variables"
        style="font-weight: bold;">MultMilling (positions, origins, code,
        frame, side[, leaf])</span></p>

        <p style="margin: 0px 0px 0px 48px;"><span class="f_Variables"
        style="font-weight: bold;">MultMilling (positions, origins, code,
        SPECIAL, category, side[, leaf])</span></p>

        <p style="margin: 0px 0px 0px 48px;"><span class="f_Variables"
        style="font-weight: bold;">MultMilling (positions, origins, code,
        AUTO)</span></p>

        <p class="p_Interligne"><span class="f_Interligne"
        style="font-weight: bold;"> </span></p>

        <p style="margin: 0px 0px 0px 24px;">or</p>

        <p style="margin: 0px 0px 0px 48px;"><span class="f_Variables"
        style="font-weight: bold;">MultMilling (positions, origin, code, frame,
        side[, leaf])</span></p>

        <p style="margin: 0px 0px 0px 48px;"><span class="f_Variables"
        style="font-weight: bold;">MultMilling (positions, origin, code,
        SPECIAL, category, side[, leaf])</span></p>

        <p style="margin: 0px 0px 0px 48px;"><span class="f_Variables"
        style="font-weight: bold;">MultMilling (positions, origin, code,
        AUTO)</span></p>

        <p><span class="f_Variables" style="font-weight: bold;"> </span></p>

        <p>Both sets are differentiated by their first 2 parameters:</p>

        <div
        style="text-align: left; text-indent: 0px; padding: 0px 0px 0px 0px; margin: 0px 0px 0px 16px;">

        <table border="0" cellpadding="0" cellspacing="0"
        style="line-height: normal;">
          <tbody>
            <tr valign="baseline">
              <td width="17"><span
                style="font-size: 10pt; font-family: 'Arial Unicode MS', 'Lucida Sans Unicode', 'Arial'; color: #000000;">&bull;</span></td>
              <td><span class="f_Variables">Milling</span> allows a unique
                value for parameters <span class="f_Variables">position</span>
                and <span class="f_Variables">origin</span>, and each of these
                parameters may be any arithmetic expression.</td>
            </tr>
          </tbody>
        </table>
        </div>

        <div
        style="text-align: left; text-indent: 0px; padding: 0px 0px 0px 0px; margin: 0px 0px 0px 16px;">

        <table border="0" cellpadding="0" cellspacing="0"
        style="line-height: normal;">
          <tbody>
            <tr valign="baseline">
              <td width="17"><span
                style="font-size: 10pt; font-family: 'Arial Unicode MS', 'Lucida Sans Unicode', 'Arial'; color: #000000;">&bull;</span></td>
              <td><span class="f_Variables">MultMilling</span> uses an <a
                href="variables.php">array variable</a> for the <span
                class="f_Variables">position</span> parameter, and either an
                array or a single value for the origin parameter (if you use a
                single value, it will be applied identically on every
                position). The maximum number of positions authorised in <span
                class="f_Variables">MultMilling</span> is <span
                style="font-weight: bold;">20</span>. By nature, the first 2
                parameters <span class="f_Variables">position</span> and <span
                class="f_Variables">origin</span> are array variables (or a
                simple variable for parameter origin); you can in no way use an
                arithmetic expression for those parameters. Of course, you can
                compute the values of the array any way you want.</td>
            </tr>
          </tbody>
        </table>
        </div>

        <p> </p>

        <p>There are important differences between millings sent to a frame, a
        <span class="f_Variables">SPECIAL</span> milling or an <span
        class="f_Variables">AUTO</span> milling:</p>

        <div
        style="text-align: left; text-indent: 0px; padding: 0px 0px 0px 0px; margin: 0px 0px 0px 17px;">

        <table border="0" cellpadding="0" cellspacing="0"
        style="line-height: normal;">
          <tbody>
            <tr valign="baseline">
              <td width="17"><span
                style="font-size: 10pt; font-family: 'Arial Unicode MS', 'Lucida Sans Unicode', 'Arial'; color: #000000;">&bull;</span></td>
              <td>With a milling sent to a frame, WinPro computes first its
                position relatively to the elements in which it is computed.
                Then it looks up, in the direction indicated by the <span
                class="f_Variables">side</span> parameter, the first profile
                belonging to the destination frame whose position matches the
                <span class="f_Variables">side</span> parameter. Finally, it
                computes the position of the milling on that profile, using the
                position offset between that profile and the origin element.
                Although this kind of milling has many restrictions, it is the
                most used.  This is because it is the simplest to use, and it
                automatically computes the relative position of the source
                element and the destination profile.</td>
            </tr>
          </tbody>
        </table>
        </div>

        <div
        style="text-align: left; text-indent: 0px; padding: 0px 0px 0px 0px; margin: 0px 0px 0px 17px;">

        <table border="0" cellpadding="0" cellspacing="0"
        style="line-height: normal;">
          <tbody>
            <tr valign="baseline">
              <td width="17"><span
                style="font-size: 10pt; font-family: 'Arial Unicode MS', 'Lucida Sans Unicode', 'Arial'; color: #000000;">&bull;</span></td>
              <td>With a <span class="f_Variables">SPECIAL</span> milling,
                WinPro works similarly, except that it looks for the first
                profile with the corresponding category. Whether this profile
                belongs to the origin element or not is irrelevant. This kind
                of milling is more flexible, but requires more work, because
                you have to set up profile categories (you can also assign
                categories dynamically...).</td>
            </tr>
          </tbody>
        </table>
        </div>

        <div
        style="text-align: left; text-indent: 0px; padding: 0px 0px 0px 0px; margin: 0px 0px 0px 17px;">

        <table border="0" cellpadding="0" cellspacing="0"
        style="line-height: normal;">
          <tbody>
            <tr valign="baseline">
              <td width="17"><span
                style="font-size: 10pt; font-family: 'Arial Unicode MS', 'Lucida Sans Unicode', 'Arial'; color: #000000;">&bull;</span></td>
              <td><span class="f_Variables">AUTO</span> millings are very
                simple: they are simply applied on the profile from which they
                are generated!</td>
            </tr>
          </tbody>
        </table>
        </div>

        <p class="p_Interligne"><span class="f_Interligne"> </span></p>

        <div
        style="text-align: center; text-indent: 0px; padding: 0px 0px 0px 0px; margin: 0px 0px 0px 0px;">

        <table align="center" cellspacing="0" cellpadding="0" bgcolor="#bfd7bf"
        border="0"
        style="background-color: #bfd7bf; border: none border-spacing:0px; border-collapse: collapse;">
          <tbody>
            <tr valign="top" align="left">
              <td width="605"
                style="width: 605px; border: solid 1px #000000;"><p
                style="margin: 0px 0px 0px 12px;"><span
                style="font-weight: bold; text-decoration: underline;">Notes:</span></p>

                <div
                style="text-align: left; text-indent: 0px; padding: 0px 0px 0px 0px; margin: 0px 0px 0px 12px;">

                <table border="0" cellpadding="0" cellspacing="0"
                style="line-height: normal;">
                  <tbody>
                    <tr valign="baseline">
                      <td width="17"><span
                        style="font-size: 10pt; font-family: 'Arial Unicode MS', 'Lucida Sans Unicode', 'Arial'; color: #000000;">&bull;</span></td>
                      <td>Usually, when you generate two ore more identical
                        millings on the same position of the same profile, only
                        one is generated. There is however an exception:
                        millings with an "absolute" origin will be generated as
                        many times as you define them. This is a design
                        decision.</td>
                    </tr>
                  </tbody>
                </table>
                </div>

                <div
                style="text-align: left; text-indent: 0px; padding: 0px 0px 0px 0px; margin: 0px 0px 0px 12px;">

                <table border="0" cellpadding="0" cellspacing="0"
                style="line-height: normal;">
                  <tbody>
                    <tr valign="baseline">
                      <td width="17"><span
                        style="font-size: 10pt; font-family: 'Arial Unicode MS', 'Lucida Sans Unicode', 'Arial'; color: #000000;">&bull;</span></td>
                      <td>WinPro will also eliminate millings outside the
                        destination profile (position &lt;= 0 or &gt;= profile
                        length). This rule does not apply to <span
                        class="f_Variables">absolute</span> millings; for those
                        millings, any position is legal, even a negative
                        position, as it may represent any value but a position
                        (e.g. number of hinges). You can also set up your
                        milling to authorize it at position 0 or position
                        length, to allow millings exactly at the profile end
                        (e.g. to mill the end of a transom).</td>
                    </tr>
                  </tbody>
                </table>
                </div>

                <div
                style="text-align: left; text-indent: 0px; padding: 0px 0px 0px 0px; margin: 0px 0px 0px 12px;">

                <table border="0" cellpadding="0" cellspacing="0"
                style="line-height: normal;">
                  <tbody>
                    <tr valign="baseline">
                      <td width="17"><span
                        style="font-size: 10pt; font-family: 'Arial Unicode MS', 'Lucida Sans Unicode', 'Arial'; color: #000000;">&bull;</span></td>
                      <td>If parameter <span class="f_Variables">side</span> is
                        preceded by symbol <span
                        class="f_Variables">-&gt;</span>, this parameter means
                        that the milling will be sent in the direction of the
                        parameter, rather than on a profile which location
                        matches the parameter.</td>
                    </tr>
                  </tbody>
                </table>
                </div>

                <div
                style="text-align: left; text-indent: 0px; padding: 0px 0px 0px 0px; margin: 0px 0px 0px 12px;">

                <table border="0" cellpadding="0" cellspacing="0"
                style="line-height: normal;">
                  <tbody>
                    <tr valign="baseline">
                      <td width="17"><span
                        style="font-size: 10pt; font-family: 'Arial Unicode MS', 'Lucida Sans Unicode', 'Arial'; color: #000000;">&bull;</span></td>
                      <td><span style="color: #000000;">For a milling from a
                        transom toward itself, when the transom has been
                        repositioned using variables </span><span
                        class="f_Variables">X0, X1, Y0, Y1</span>, you will
                        have to apply again the same correction as the values
                        used into the transom cutting rule. To avoid this
                        behavior, the <span class="f_Variables">AUTO
                        </span>syntax is strongly suggested.</td>
                    </tr>
                  </tbody>
                </table>
                </div>

                <div
                style="text-align: left; text-indent: 0px; padding: 0px 0px 0px 0px; margin: 0px 0px 0px 12px;">

                <table border="0" cellpadding="0" cellspacing="0"
                style="line-height: normal;">
                  <tbody>
                    <tr valign="baseline">
                      <td width="17"><span
                        style="font-size: 10pt; font-family: 'Arial Unicode MS', 'Lucida Sans Unicode', 'Arial'; color: #000000;">&bull;</span></td>
                      <td>WinPro do not consider the positioning of a French
                        mullion when this one is moved using variables <span
                        class="f_Variables">X0, X1, Y0, Y1</span>. For the
                        millings to be correct onto such a profile, it should
                        imperatively be also assigned to the correct French
                        mullion category into the profile set up, AND the
                        "French mullion" box should be checked into the Profile
                        tab of the corresponding rule within the sash
                      frame.</td>
                    </tr>
                  </tbody>
                </table>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
        </div>

        <p style="text-align: center; margin: 0px 0px 0px 1px;"><span
        style="font-size: 5pt; color: #000000;"> </span></p>

        <div
        style="text-align: center; text-indent: 0px; padding: 0px 0px 0px 0px; margin: 0px 0px 0px 0px;">

        <table align="center" cellspacing="0" cellpadding="2" bgcolor="#fff7ef"
        border="1"
        style="background-color: #fff7ef; border: solid 2px #c0c0c0; border-spacing:0px; border-collapse: collapse;">
          <tbody>
            <tr valign="middle" align="left">
              <td width="113"
                style="width: 113px; border: solid 1px #c0c0c0;"><p
                style="text-align: center;"><span
                style="font-weight: bold; color: #000000;">Parameter</span></p>
              </td>
              <td width="491"
                style="width: 491px; border: solid 1px #c0c0c0;"><p
                style="margin: 0px 0px 0px 11px;"><span
                style="font-weight: bold;">Description</span></p>
              </td>
            </tr>
            <tr valign="middle" align="left">
              <td width="113"
                style="width: 113px; border: solid 1px #c0c0c0;"><p
                style="text-align: center;"><span
                class="f_Variables">position</span></p>
              </td>
              <td width="491"
                style="width: 491px; border: solid 1px #c0c0c0;"><p
                style="margin: 0px 0px 0px 11px;"><span
                style="color: #000000;">Distance, in mm, since the </span><span
                style="font-family: 'Courier New'; color: #0000ff;">origin</span><span
                style="color: #000000;">point</span></p>
              </td>
            </tr>
            <tr valign="middle" align="left">
              <td width="113"
                style="width: 113px; border: solid 1px #c0c0c0;"><p
                style="text-align: center;"><span
                class="f_Variables">positions</span></p>
              </td>
              <td width="491"
                style="width: 491px; border: solid 1px #c0c0c0;"><p
                style="margin: 0px 0px 0px 11px;"><span
                style="color: #000000;">List of distances, in mm, since the
                </span><span
                style="font-family: 'Courier New'; color: #0000ff;">origin</span><span
                style="color: #000000;">point.</span></p>
              </td>
            </tr>
            <tr valign="middle" align="left">
              <td width="113"
                style="width: 113px; border: solid 1px #c0c0c0;"><p
                style="text-align: center;"><span
                class="f_Variables">origin</span></p>
              </td>
              <td width="491"
                style="width: 491px; border: solid 1px #c0c0c0;"><p
                style="margin: 0px 0px 0px 11px;"><span
                style="color: #000000;">Point of origin: </span><span
                style="font-family: 'Courier New'; color: #0000ff;">top</span><span
                style="color: #000000;">, </span><span
                style="font-family: 'Courier New'; color: #0000ff;">bottom</span><span
                style="color: #000000;">, </span><span
                style="font-family: 'Courier New'; color: #0000ff;">left</span><span
                style="color: #000000;">, </span><span
                style="font-family: 'Courier New'; color: #0000ff;">right</span><span
                style="color: #000000;">, </span><span
                style="font-family: 'Courier New'; color: #0000ff;">center</span><span
                style="color: #000000;">or </span><span
                style="font-family: 'Courier New'; color: #0000ff;">absolute</span><span
                style="color: #000000;">.</span></p>
              </td>
            </tr>
            <tr valign="middle" align="left">
              <td width="113"
                style="width: 113px; border: solid 1px #c0c0c0;"><p
                style="text-align: center;"><span
                class="f_Variables">origins</span></p>
              </td>
              <td width="491"
                style="width: 491px; border: solid 1px #c0c0c0;"><p
                style="margin: 0px 0px 0px 11px;"><span
                style="color: #000000;">List of points of origin; the number of
                points must be equal to the number of </span><span
                style="font-family: 'Courier New'; color: #0000ff;">positions</span><span
                style="color: #000000;">.</span>.</p>
              </td>
            </tr>
            <tr valign="middle" align="left">
              <td width="113"
                style="width: 113px; border: solid 1px #c0c0c0;"><p
                style="text-align: center;"><span
                style="font-size: 5pt; font-family: 'Courier New'; color: #0000ff;"> </span></p>

                <p style="text-align: center;"><span
                class="f_Variables">type</span></p>
              </td>
              <td width="491"
                style="width: 491px; border: solid 1px #c0c0c0;"><p
                style="margin: 0px 0px 0px 11px;"><span
                style="color: #000000;">Milling type: </span><span
                style="font-family: 'Courier New'; color: #0000ff;">simple </span><span
                style="color: #000000;">or </span><span
                style="font-family: 'Courier New'; color: #0000ff;">composed</span><span
                style="color: #000000;">. The next parameter must have a
                milling code which exists in the corresponding <a
                href="usinages.php">milling table</a> or <a
                href="groupesusinages.php">composed milling table</a>.</span></p>
              </td>
            </tr>
            <tr valign="middle" align="left">
              <td width="113"
                style="width: 113px; border: solid 1px #c0c0c0;"><p
                style="text-align: center;"><span
                class="f_Variables">code</span></p>
              </td>
              <td width="491"
                style="width: 491px; border: solid 1px #c0c0c0;"><p
                style="margin: 0px 0px 0px 11px;"><span
                style="color: #000000;">Milling code (it must exists in the
                correct milling table).</span></p>
              </td>
            </tr>
            <tr valign="middle" align="left">
              <td width="113"
                style="width: 113px; border: solid 1px #c0c0c0;"><p
                style="text-align: center;"><span
                class="f_Variables">frame</span></p>
              </td>
              <td width="491"
                style="width: 491px; border: solid 1px #c0c0c0;"><p
                style="margin: 0px 0px 0px 11px;"><span
                style="color: #000000;">Possible values are: </span><span
                style="font-family: 'Courier New'; color: #0000ff;">OuterFrame</span><span
                style="color: #000000;">, </span><span
                style="font-family: 'Courier New'; color: #0000ff;">Sash</span><span
                style="color: #000000;">, </span><span
                style="font-family: 'Courier New'; color: #0000ff;">Mullion</span><span
                style="color: #000000;">, </span><span
                style="font-family: 'Courier New'; color: #0000ff;">SashReinforcement</span><span
                style="color: #000000;">, </span><span
                style="font-family: 'Courier New'; color: #0000ff;">OuterFrameReinforcement</span><span
                style="color: #000000;">, </span><span
                style="font-family: 'Courier New'; color: #0000ff;">MullionReinforcement</span><span
                style="color: #000000;">. The milling will be sent to the
                profile corresponding to the given type. Please note that the
                profile type (defined in the <a href="profils.php">profile
                table</a>) must be among one of these categories: </span><span
                style="font-weight: bold; color: #000000;">Main
                profile</span><span style="color: #000000;">, </span><span
                style="font-weight: bold; color: #000000;">Steel</span><span
                style="color: #000000;">, </span><span
                style="font-weight: bold; color: #000000;">Mullion</span><span
                style="color: #000000;">, </span><span
                style="font-weight: bold; color: #000000;">Mullion
                reinforcement</span><span style="color: #000000;">. Category
                </span><span style="font-weight: bold; color: #000000;">Main
                profile</span><span style="color: #000000;">is connected to the
                parameter </span><span
                style="font-family: 'Courier New'; color: #0000ff;">OuterFrame</span><span
                style="color: #000000;">and </span><span
                style="font-family: 'Courier New'; color: #0000ff;">Sash</span><span
                style="color: #000000;">; category </span><span
                style="font-weight: bold; color: #000000;">Reinforcement</span><span
                style="color: #000000;">is connected to </span><span
                style="font-family: 'Courier New'; color: #0000ff;">Reinforcement</span><span
                style="color: #000000;">and </span><span
                style="font-family: 'Courier New'; color: #0000ff;">MullionReinforcement</span><span
                style="color: #000000;">.</span></p>
              </td>
            </tr>
            <tr valign="middle" align="left">
              <td width="113"
                style="width: 113px; border: solid 1px #c0c0c0;"><p
                style="text-align: center;"><span
                style="font-size: 5pt; font-family: 'Courier New'; color: #0000ff;"></span><span
                class="f_Variables">side</span></p>
              </td>
              <td width="491"
                style="width: 491px; border: solid 1px #c0c0c0;"><p
                style="margin: 0px 0px 0px 11px;"><span
                style="color: #000000;">Side of the frame towards which the
                milling must be sent. Possible values are: </span><span
                style="font-family: 'Courier New'; color: #0000ff;">top</span><span
                style="color: #000000;">, </span><span
                style="font-family: 'Courier New'; color: #0000ff;">bottom</span><span
                style="color: #000000;">, </span><span
                style="font-family: 'Courier New'; color: #0000ff;">left</span><span
                style="color: #000000;">,</span><span
                style="font-size: 11pt; color: #0000ff;"></span><span
                style="font-family: 'Courier New'; color: #0000ff;">right</span><span
                style="font-size: 11pt; font-family: 'Courier New'; font-weight: bold; color: #0000ff;">.</span><span
                style="color: #000000;">You can also add the sign </span><span
                style="font-family: 'Courier New'; color: #0000ff;">-&gt;</span><span
                style="color: #000000;">in front of this parameter
                (</span><span
                style="font-family: 'Courier New'; color: #0000ff;">-&gt;top</span><span
                style="color: #000000;">, </span><span
                style="font-family: 'Courier New'; color: #0000ff;">-&gt;bottom</span><span
                style="color: #000000;">, </span><span
                style="font-family: 'Courier New'; color: #0000ff;">-&gt;left</span><span
                style="color: #000000;">,</span><span
                style="font-size: 11pt; color: #0000ff;"></span><span
                style="font-family: 'Courier New'; color: #0000ff;">-&gt;right</span><span
                style="color: #000000;">). In this case, the parameter simply
                indicates a direction where the milling is sent; the profile
                receiving the milling may be at any position (see fourth
                example).</span></p>
              </td>
            </tr>
            <tr valign="middle" align="left">
              <td width="113"
                style="width: 113px; border: solid 1px #c0c0c0;"><p
                style="text-align: center;"><span
                class="f_Variables">leaf</span></p>
              </td>
              <td width="491"
                style="width: 491px; border: solid 1px #c0c0c0;"><p
                style="margin: 0px 0px 0px 11px;"><span
                style="color: #000000;">Index of the leaf where the milling
                must be sent (1 to n, starting from left or bottom)</span></p>
              </td>
            </tr>
            <tr valign="middle" align="left">
              <td width="113"
                style="width: 113px; border: solid 1px #c0c0c0;"><p
                style="text-align: center;"><span
                class="f_Variables">SPECIAL</span></p>
              </td>
              <td width="491"
                style="width: 491px; border: solid 1px #c0c0c0;"><p
                style="margin: 0px 0px 0px 11px;"><span
                style="color: #000000;">If this parameter is used, the milling
                is not sent toward a specific frame, but instead toward a
                profile with a category matching the one used as parameter into
                the milling instruction. This lets you send millings toward all
                kind of profiles, whatever their uses are.</span></p>
              </td>
            </tr>
            <tr valign="middle" align="left">
              <td width="113"
                style="width: 113px; border: solid 1px #c0c0c0;"><p
                style="text-align: center;"><span
                class="f_Variables">category</span></p>
              </td>
              <td width="491"
                style="width: 491px; border: solid 1px #c0c0c0;"><p
                style="margin: 0px 0px 0px 11px;"><span
                style="color: #000000;">Used only with the parameter
                </span><span
                style="font-family: 'Courier New'; color: #0000ff;">SPECIAL</span><span
                style="color: #000000;">, this parameter gives the category of
                profile where the milling must be applied.</span></p>

                <p style="margin: 0px 0px 0px 11px;"><span
                style="font-weight: bold; color: #000000; text-decoration: underline;">Remark</span><span
                style="font-weight: bold; color: #000000;"></span><span
                style="color: #000000;">: If two profiles with the same
                category are located at the same position, the milling will be
                sent on the first one found by WinPro.</span></p>
              </td>
            </tr>
            <tr valign="middle" align="left">
              <td width="113"
                style="width: 113px; border: solid 1px #c0c0c0;"><p
                style="text-align: center;"><span
                class="f_Variables">AUTO</span></p>
              </td>
              <td width="491"
                style="width: 491px; border: solid 1px #c0c0c0;"><p
                style="margin: 0px 0px 0px 11px;"><span
                style="color: #000000;">If this parameter is used, the milling
                is applied directly onto the profile where it is
                generated.</span></p>
              </td>
            </tr>
          </tbody>
        </table>
        </div>

        <p style="text-align: center; margin: 0px 0px 0px 1px;"><span
        style="font-size: 5pt; color: #000000;"> </span></p>

        <p style="margin: 0px 0px 0px 24px;"><span
        style="color: #000000; text-decoration: underline;">Examples:</span></p>

        <p style="margin: 0px 0px 0px 48px;"><span style="color: #000000;">1.
        In a sash or fitting formula:</span></p>

        <p style="margin: 0px 0px 0px 64px;"><span
        style="font-family: 'Courier New'; color: #0000ff;"># Milling of a
        handle on leaf 2 of a double sash French window, opening right
        </span></p>

        <p style="margin: 0px 0px 0px 64px;"><span
        style="font-family: 'Courier New'; color: #0000ff;">Milling (400,
        bottom, simple, HANDLE, sash, left, 2)</span></p>

        <p style="margin: 0px 0px 0px 64px;"><span
        style="font-family: 'Courier New'; color: #0000ff;"># Milling of a top
        hinge (simple sash opening left)</span></p>

        <p class="p_Interligne" style="margin: 0px 0px 0px 63px;"><span
        style="font-family: 'Courier New'; color: #0000ff;">Milling (80, top,
        simple, HINGE, OuterFrame, left)</span></p>

        <p class="p_Interligne"><span class="f_Interligne"> </span></p>

        <p style="margin: 0px 0px 0px 48px;"><span style="color: #000000;">2.
        In a transom formula:</span></p>

        <p style="margin: 0px 0px 0px 63px;"><span
        style="font-family: 'Courier New'; color: #0000ff;"># Milling of the
        transom hole for a vertical transom in an outer frame </span></p>

        <p style="margin: 0px 0px 0px 63px;"><span
        style="font-family: 'Courier New'; color: #0000ff;">Milling (0, center,
        simple, TRANSOM, OuterFrame, bottom)</span></p>

        <p style="margin: 0px 0px 0px 63px;"><span
        style="font-family: 'Courier New'; color: #0000ff;">Milling (0, center,
        simple, TRANSOM, OuterFrame, top)</span></p>

        <p style="margin: 0px 0px 0px 63px;"><span
        style="font-family: 'Courier New'; color: #0000ff;"># Milling of
        weather holes on a horizontal transom</span></p>

        <p style="margin: 0px 0px 0px 63px;"><span
        style="font-family: 'Courier New'; color: #0000ff;">Milling (100, left,
        simple, WEATHER HOLE, auto)</span></p>

        <p style="margin: 0px 0px 0px 63px;"><span
        style="font-family: 'Courier New'; color: #0000ff;">Milling (100,
        right, simple, WEATHER HOLE, auto)</span></p>

        <p style="margin: 0px 0px 0px 63px;"><span
        style="font-family: 'Courier New'; color: #0000ff;"># Milling of a
        weather hole, with a second parameter associated</span></p>

        <p style="margin: 0px 0px 0px 63px;"><span
        style="font-family: 'Courier New'; color: #0000ff;">pos : 2</span></p>

        <p style="margin: 0px 0px 0px 63px;"><span
        style="font-family: 'Courier New'; color: #0000ff;">org : 2</span></p>

        <p style="margin: 0px 0px 0px 63px;"><span
        style="font-family: 'Courier New'; color: #0000ff;">pos[1] :=
        100</span></p>

        <p style="margin: 0px 0px 0px 63px;"><span
        style="font-family: 'Courier New'; color: #0000ff;">pos[2] :=
        1</span></p>

        <p style="margin: 0px 0px 0px 63px;"><span
        style="font-family: 'Courier New'; color: #0000ff;">org[1] :=
        left</span></p>

        <p style="margin: 0px 0px 0px 63px;"><span
        style="font-family: 'Courier New'; color: #0000ff;">org[2] :=
        absolute</span></p>

        <p class="p_Interligne" style="margin: 0px 0px 0px 63px;"><span
        style="font-family: 'Courier New'; color: #0000ff;">MultMilling (pos,
        org, WEATHER HOLE, auto)</span></p>

        <p class="p_Interligne"><span class="f_Interligne"> </span></p>

        <p style="margin: 0px 0px 0px 48px;"><span style="color: #000000;">3.
        Milling from the outer frame towards a peripheral profile of category
        100</span></p>

        <p class="p_Interligne" style="margin: 0px 0px 0px 63px;"><span
        style="font-family: 'Courier New'; color: #0000ff;">Milling (400,
        bottom, simple, HOLE 12, special, 100, side)</span></p>

        <p class="p_Interligne"><span class="f_Interligne"> </span></p>

        <p style="margin: 0px 0px 0px 48px;"><span style="color: #000000;">4.
        Milling from a peripheral profile towards the right outer frame of
        category 110</span></p>

        <p style="margin: 0px 0px 0px 62px;"><span
        style="font-family: 'Courier New'; color: #0000ff;">Milling (400,
        bottom, simple, HOLE 8, special, 110, -&gt;left)</span></p>

        <p><span style="color: #000000;"> </span></p>
      </td>
    </tr>
  </tbody>
</table>
</div>

<div class="FRA">
<!-- Placeholder for topic body. -->

<table width="100%" border="0" cellspacing="0" cellpadding="5">
  <tbody>
    <tr valign="top">
      <td align="left"><p> </p>

        <p>Ces instructions vous permettent de définir les opération d'usinage
        à appliquer sur les profils composant le châssis (module).</p>

        <p>Fondamentalement, WinPro vous permet de définir vos usinages d'un
        point de vue logique, sans tenir compte des contraintes liées à chaque
        centre d'usinage. Par exemple, si un usinage doit être déclenché à
        partir d'une quincaillerie, mais doit s'appliquer sur le dormant ou une
        traverse de dormant, il vous suffit de spécifier la position de
        l'usinage par rapport à la quincaillerie; WinPro se chargera de
        reporter la position de l'usinage sur le dormant, en tenant compte des
        positions relatives du dormant et de la quincaillerie. De même, vous
        pouvez indiquer la position de l'usinage par rapport au point de
        référence qui vous convient le mieux (haut, bas, gauche, droite ou
        centre), sans tenir compte des contraintes liées à votre centre
        d'usinage.</p>

        <p>Afin de répondre aux différents besoins d'usinage, WinPro vous offre
        deux types d'instructions, dont chacune supporte plusieurs types de
        paramètres.</p>

        <p>Ces instructions s'utilisent toujours selon le même schéma: vous
        indiquez, dans l'ordre, la position de l'usinage par rapport à son
        origine, le code d'usinage, et enfin l'endroit où l'usinage doit être
        réalisé.</p>

        <p class="p_Interligne"><span class="f_Interligne"> </span></p>

        <p style="margin: 0px 0px 0px 24px;">La première instruction, <span
        class="f_Variables">Usinage</span>, s'utilise selon l'une des syntaxes
        suivantes:</p>

        <p style="margin: 0px 0px 0px 48px;"><strong><span
        class="f_Variables">Usinage (position, origine, type, code, cadre,
        bord[, vantail])</span></strong></p>

        <p style="margin: 0px 0px 0px 48px;"><strong><span
        class="f_Variables">Usinage (position, origine, type, code, SPECIAL,
        categorie, bord[, vantail])</span></strong></p>

        <p style="margin: 0px 0px 0px 48px;"><strong><span
        class="f_Variables">Usinage (position, origine, type, code,
        AUTO)</span></strong></p>

        <p class="p_Interligne"><span class="f_Interligne"> </span></p>

        <p style="margin: 0px 0px 0px 24px;">La deuxième instruction, <span
        class="f_Variables">UsinageExt</span>, s'utilise selon l'une des
        syntaxes suivantes:</p>

        <p style="margin: 0px 0px 0px 48px;"><strong><span
        class="f_Variables">UsinageExt (positions, origines, code, cadre,
        bord[, vantail])</span></strong></p>

        <p style="margin: 0px 0px 0px 48px;"><strong><span
        class="f_Variables">UsinageExt (positions, origines, code, SPECIAL,
        categorie, bord[, vantail])</span></strong></p>

        <p style="margin: 0px 0px 0px 48px;"><strong><span
        class="f_Variables">UsinageExt (positions, origines, code,
        AUTO)</span></strong></p>

        <p class="p_Interligne"><span class="f_Interligne"> </span></p>

        <p style="margin: 0px 0px 0px 24px;">ou</p>

        <p style="margin: 0px 0px 0px 48px;"><strong><span
        class="f_Variables">UsinageExt (positions, origine, code, cadre, bord[,
        vantail])</span></strong></p>

        <p style="margin: 0px 0px 0px 48px;"><strong><span
        class="f_Variables">UsinageExt (positions, origine, code, SPECIAL,
        categorie, bord[, vantail])</span></strong></p>

        <p style="margin: 0px 0px 0px 48px;"><strong><span
        class="f_Variables">UsinageExt (positions, origine, code,
        AUTO)</span></strong></p>

        <p style="margin: 0px 0px 0px 40px;"><span class="f_Variables"
        style="font-weight: bold;"> </span></p>

        <p><span
        style="font-size: 4pt; font-family: 'Courier New'; color: #0000ff;"></span>Les
        deux types d'instruction se distinguent au niveau de leurs deux
        premiers paramètres: </p>

        <div
        style="text-align: left; text-indent: 0px; padding: 0px 0px 0px 0px; margin: 0px 0px 0px 14px;">

        <table border="0" cellpadding="0" cellspacing="0"
        style="line-height: normal;">
          <tbody>
            <tr valign="baseline">
              <td width="17"><span
                style="font-size: 10pt; font-family: 'Arial Unicode MS', 'Lucida Sans Unicode', 'Arial'; color: #000000;">&bull;</span></td>
              <td><span style="color: #0000ff;">Usinage</span> supporte une
                valeur unique pour les paramètres <span
                style="color: #0000ff;">position</span> et <span
                style="color: #0000ff;">origine</span>, et chacun de ces
                paramètres peut être une expression arithmétique
              quelconque.</td>
            </tr>
          </tbody>
        </table>
        </div>

        <div
        style="text-align: left; text-indent: 0px; padding: 0px 0px 0px 0px; margin: 0px 0px 0px 14px;">

        <table border="0" cellpadding="0" cellspacing="0"
        style="line-height: normal;">
          <tbody>
            <tr valign="baseline">
              <td width="17"><span
                style="font-size: 10pt; font-family: 'Arial Unicode MS', 'Lucida Sans Unicode', 'Arial'; color: #000000;">&bull;</span></td>
              <td><span class="f_Variables">UsinageExt</span> utilise une
                variable tableau pour le paramètre <span
                style="color: #0000ff;">position</span>, et soit une <a
                href="variables.php">variable tableau</a>, soit une valeur
                simple pour le paramètre <span
                style="color: #0000ff;">origine</span> (si vous utilisez une
                valeur simple, elle sera répercutée à l'identique sur chaque
                position). Le nombre maximum de valeurs autorisées pour <span
                class="f_Variables">UsinageExt</span> est de <span
                style="font-weight: bold;">20</span>. De par leur nature, les
                deux paramètres <span style="color: #0000ff;">position</span>
                et <span style="color: #0000ff;">origine</span> sont
                nécessairement des variables tableau (éventuellement une
                variable simple pour la paramètre origine), mais en aucun cas
                vous ne pouvez utiliser une expression arithmétique pour ces
                paramètres. Bien entendu, vous pouvez utiliser toute expression
                pour calculer le contenu de ces variables.</td>
            </tr>
          </tbody>
        </table>
        </div>

        <p> </p>

        <p>Notez bien que les usinages vers un cadre, un usinage <span
        class="f_Variables">SPECIAL</span>, ou un usinage <span
        style="color: #0000ff;">AUTO</span> sont calculés de manières
        sensiblement différentes:</p>

        <div
        style="text-align: left; text-indent: 0px; padding: 0px 0px 0px 0px; margin: 0px 0px 0px 14px;">

        <table border="0" cellpadding="0" cellspacing="0"
        style="line-height: normal;">
          <tbody>
            <tr valign="baseline">
              <td width="17"><span
                style="font-size: 10pt; font-family: 'Arial Unicode MS', 'Lucida Sans Unicode', 'Arial'; color: #000000;">&bull;</span></td>
              <td>Pour un usinage vers un cadre, WinPro calcule d'abord la
                position par rapport à l'élément depuis la formule duquel
                l'usinage est calculé; ensuite, il cherche, dans la direction
                donnée par le paramètre <span class="f_Variables">bord</span>,
                le premier profil appartenant au cadre de destination; enfin,
                il calcule la position de l'usinage sur ce profil, en tenant
                compte de la position relative de l'élément d'origine et du
                profil de destination. Ce type d'usinage est d'un usage assez
                restrictif (bien qu'il soit le plus utilisé), car l'usinage
                part uniquement d'un ouvrant, d'une quincaillerie ou d'une
                traverse vers un dormant ou vice versa. Par contre, WinPro
                gérera lui-même l'envoi de l'usinage vers les traverses plutôt
                que vers les cadres, lorsque la configuration du châssis
                l'exige.</td>
            </tr>
          </tbody>
        </table>
        </div>

        <div
        style="text-align: left; text-indent: 0px; padding: 0px 0px 0px 0px; margin: 0px 0px 0px 14px;">

        <table border="0" cellpadding="0" cellspacing="0"
        style="line-height: normal;">
          <tbody>
            <tr valign="baseline">
              <td width="17"><span
                style="font-size: 10pt; font-family: 'Arial Unicode MS', 'Lucida Sans Unicode', 'Arial'; color: #000000;">&bull;</span></td>
              <td>Pour un usinage <span class="f_Variables">SPECIAL</span>,
                WinPro part aussi de l'élément depuis la formule duquel
                l'usinage est défini, dans la direction spécifiée par le
                paramètre bord, jusqu'à ce qu'il trouve un profil dont la
                catégorie numérique correspond à la catégorie donnée dans le
                paramètre qui suit le paramètre <span
                class="f_Variables">SPECIAL</span>. Il n'y a donc pas de
                restriction sur l'origine ou la destination de l'usinage: tout
                profil est susceptible de recevoir l'usinage, pourvu qu'il soit
                de la bonne catégorie numérique.</td>
            </tr>
          </tbody>
        </table>
        </div>

        <div
        style="text-align: left; text-indent: 0px; padding: 0px 0px 0px 0px; margin: 0px 0px 0px 14px;">

        <table border="0" cellpadding="0" cellspacing="0"
        style="line-height: normal;">
          <tbody>
            <tr valign="baseline">
              <td width="17"><span
                style="font-size: 10pt; font-family: 'Arial Unicode MS', 'Lucida Sans Unicode', 'Arial'; color: #000000;">&bull;</span></td>
              <td>Les usinages <span style="color: #0000ff;">AUTO</span> sont
                les plus simples: WinPro ne va pas plus loin que le profil
                depuis la formule duquel l'usinage est généré.</td>
            </tr>
          </tbody>
        </table>
        </div>

        <p class="p_Interligne"><span class="f_Interligne"> </span></p>

        <p><span style="font-size: 5pt;"> </span></p>

        <div
        style="text-align: center; text-indent: 0px; padding: 0px 0px 0px 0px; margin: 0px 0px 0px 0px;">

        <table align="center" cellspacing="0" cellpadding="0" bgcolor="#bfd7bf"
        border="0"
        style="background-color: #bfd7bf; border: none border-spacing:0px; border-collapse: collapse;">
          <tbody>
            <tr valign="top" align="left">
              <td width="605"
                style="width: 605px; border: solid 1px #000000;"><p
                style="margin: 0px 0px 0px 13px;"><span
                style="font-weight: bold; text-decoration: underline;">Remarques</span><span
                style="text-decoration: underline;">:</span></p>

                <div
                style="text-align: left; text-indent: 0px; padding: 0px 0px 0px 0px; margin: 0px 0px 0px 14px;">

                <table border="0" cellpadding="0" cellspacing="0"
                style="line-height: normal;">
                  <tbody>
                    <tr valign="baseline">
                      <td width="17"><span
                        style="font-size: 10pt; font-family: 'Arial Unicode MS', 'Lucida Sans Unicode', 'Arial'; color: #000000;">&bull;</span></td>
                      <td>En général, si vous générez deux usinages (ou plus)
                        strictement identiques sur un même profil, WinPro ne
                        retiendra que le premier d'entre eux. Il y a toutefois
                        une exception importante: si l'origine de l'usinage est
                        de type 'absolu', WinPro produira autant d'usinages que
                        vous en générerez. Il s'agît là d'une caractéristique
                        voulue.</td>
                    </tr>
                  </tbody>
                </table>
                </div>

                <div
                style="text-align: left; text-indent: 0px; padding: 0px 0px 0px 0px; margin: 0px 0px 0px 14px;">

                <table border="0" cellpadding="0" cellspacing="0"
                style="line-height: normal;">
                  <tbody>
                    <tr valign="baseline">
                      <td width="17"><span
                        style="font-size: 10pt; font-family: 'Arial Unicode MS', 'Lucida Sans Unicode', 'Arial'; color: #000000;">&bull;</span></td>
                      <td>Il faut aussi savoir que WinPro éliminera par défaut
                        les usinages qui tombent en dehors d'un profil. La
                        position d'un usinage doit donc être supérieure à 0, et
                        inférieure à la longueur du profil. Les usinages <span
                        style="color: #0000ff;">absolus</span> font toutefois
                        exception à cette règle: là, vous pouvez même définir
                        une position négative! (en fait, un usinage <span
                        style="color: #0000ff;">absolu</span> ne représente pas
                        toujours une position; souvent, il représente une
                        valeur à utiliser de manière libre, p.ex. le nombre de
                        charnières). Vous pouvez également cocher une case sur
                        le dialogue de définition de l'usinage, 'Autoriser
                        l'usinage à la position 0', pour autoriser des usinages
                        exactement en bout de barre (mais pas au-delà), par
                        exemple des fraisages de traverse.</td>
                    </tr>
                  </tbody>
                </table>
                </div>

                <div
                style="text-align: left; text-indent: 0px; padding: 0px 0px 0px 0px; margin: 0px 0px 0px 14px;">

                <table border="0" cellpadding="0" cellspacing="0"
                style="line-height: normal;">
                  <tbody>
                    <tr valign="baseline">
                      <td width="17"><span
                        style="font-size: 10pt; font-family: 'Arial Unicode MS', 'Lucida Sans Unicode', 'Arial'; color: #000000;">&bull;</span></td>
                      <td>Si le paramètre <span
                        style="color: #0000ff;">bord</span> est précédé du
                        symbole<span style="color: #0000ff;">-&gt;</span>, ce
                        paramètre n'indique plus vers quel côté de cadre
                        envoyer l'usinage, mais bien dans quelle direction le
                        profil de destination doit être recherché.</td>
                    </tr>
                  </tbody>
                </table>
                </div>

                <div
                style="text-align: left; text-indent: 0px; padding: 0px 0px 0px 0px; margin: 0px 0px 0px 14px;">

                <table border="0" cellpadding="0" cellspacing="0"
                style="line-height: normal;">
                  <tbody>
                    <tr valign="baseline">
                      <td width="17"><span
                        style="font-size: 10pt; font-family: 'Arial Unicode MS', 'Lucida Sans Unicode', 'Arial'; color: #000000;">&bull;</span></td>
                      <td>Pour un usinage paramétré dans une formule de
                        traverse a destination de cette même traverse,  et
                        lorsque la traverse a été repositionnée à l'aide des
                        variables <span class="f_Variables">X0, X1, Y0,
                        Y1</span>, il est nécessaire de rappeler, dans la
                        formule où se trouve l'instruction <span
                        class="f_Variables">Usinage</span>, les mêmes valeurs
                        <span class="f_Variables">X0, X1, Y0, Y1</span> que
                        vous avez attribué dans la formule de débit de cette
                        traverse.</td>
                    </tr>
                  </tbody>
                </table>
                </div>

                <p style="margin: 0px 0px 0px 27px;">Pour éviter cette
                contrainte, l'usinage de type <span
                style="color: #0000ff;">AUTO</span> est suggéré.</p>

                <div
                style="text-align: left; text-indent: 0px; padding: 0px 0px 0px 0px; margin: 0px 0px 0px 14px;">

                <table border="0" cellpadding="0" cellspacing="0"
                style="line-height: normal;">
                  <tbody>
                    <tr valign="baseline">
                      <td width="17"><span
                        style="font-size: 10pt; font-family: 'Arial Unicode MS', 'Lucida Sans Unicode', 'Arial'; color: #000000;">&bull;</span></td>
                      <td>Winpro ne tient pas compte du paramétrage du
                        repositionnement du mauclair afin de déterminer la
                        position des usinages envoyés sur celui-ci. Pour qu'un
                        mauclair puisse être usiné, il faut impérativement
                        l'avoir déclaré en tant que tel au niveau du choix de
                        la catégorie dans le profil ET il faut également cocher
                        la case "Mauclair" de l'onglet Profil du paramétrage
                        ouvrant pour le composant.</td>
                    </tr>
                  </tbody>
                </table>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
        </div>

        <p><span style="font-size: 5pt;"> </span></p>

        <div
        style="text-align: center; text-indent: 0px; padding: 0px 0px 0px 0px; margin: 0px 0px 0px 0px;">

        <table align="center" cellspacing="0" cellpadding="2" bgcolor="#fff7ef"
        border="1"
        style="background-color: #fff7ef; border: solid 2px #c0c0c0; border-spacing:0px; border-collapse: collapse;">
          <tbody>
            <tr valign="middle" align="left">
              <td width="113"
                style="width: 113px; border: solid 1px #c0c0c0;"><p
                style="text-align: center;"><span
                style="font-weight: bold;">Paramètre</span></p>
              </td>
              <td width="491"
                style="width: 491px; border: solid 1px #c0c0c0;"><p
                style="margin: 0px 0px 0px 13px;"><span
                style="font-weight: bold;">Description</span></p>
              </td>
            </tr>
            <tr valign="middle" align="left">
              <td width="113"
                style="width: 113px; border: solid 1px #c0c0c0;"><p
                style="text-align: center;"><span
                class="f_Variables">position</span></p>
              </td>
              <td width="491"
                style="width: 491px; border: solid 1px #c0c0c0;"><p
                style="margin: 0px 0px 0px 13px;">Distance de l'usinage, en mm,
                depuis le point <span
                style="color: #0000ff;">origine</span>.</p>
              </td>
            </tr>
            <tr valign="middle" align="left">
              <td width="113"
                style="width: 113px; border: solid 1px #c0c0c0;"><p
                style="text-align: center;"><span
                class="f_Variables">positions</span></p>
              </td>
              <td width="491"
                style="width: 491px; border: solid 1px #c0c0c0;"><p
                style="margin: 0px 0px 0px 13px;">Liste de distances, en mm,
                depuis le point <span
                style="color: #0000ff;">origine</span>.</p>
              </td>
            </tr>
            <tr valign="middle" align="left">
              <td width="113"
                style="width: 113px; border: solid 1px #c0c0c0;"><p
                style="text-align: center;"><span
                class="f_Variables">origine</span></p>
              </td>
              <td width="491"
                style="width: 491px; border: solid 1px #c0c0c0;"><p
                style="margin: 0px 0px 0px 13px;">Point d'origine: <span
                style="color: #0000ff;">Haut</span>, <span
                style="color: #0000ff;">Bas</span>, <span
                style="color: #0000ff;">Gauche</span>, <span
                style="color: #0000ff;">Droite</span>, <span
                style="color: #0000ff;">Centre</span> ou <span
                style="color: #0000ff;">Absolu</span>.</p>
              </td>
            </tr>
            <tr valign="middle" align="left">
              <td width="113"
                style="width: 113px; border: solid 1px #c0c0c0;"><p
                style="text-align: center;"><span
                class="f_Variables">origines</span></p>
              </td>
              <td width="491"
                style="width: 491px; border: solid 1px #c0c0c0;"><p
                style="margin: 0px 0px 0px 13px;">Liste de points d'origine; le
                nombre de points doit être égal au nombre de <span
                style="color: #0000ff;">positions</span>.</p>
              </td>
            </tr>
            <tr valign="middle" align="left">
              <td width="113"
                style="width: 113px; border: solid 1px #c0c0c0;"><p
                style="text-align: center;"><span
                style="font-size: 5pt; font-family: 'Courier New'; color: #0000ff;"> </span></p>

                <p style="text-align: center;"><span
                class="f_Variables">type</span></p>
              </td>
              <td width="491"
                style="width: 491px; border: solid 1px #c0c0c0;"><p
                style="margin: 0px 0px 0px 13px;">Type d'usinage: <span
                style="color: #0000ff;">Simple</span> ou <span
                style="color: #0000ff;">Compose</span>. Le code d'usinage qui
                suit doit selon le cas se trouver dans la <a
                href="usinages.php">table des usinages simples</a> ou des <a
                href="groupesusinages.php">usinages composés</a>.</p>
              </td>
            </tr>
            <tr valign="middle" align="left">
              <td width="113"
                style="width: 113px; border: solid 1px #c0c0c0;"><p
                style="text-align: center;"><span
                class="f_Variables">code</span></p>
              </td>
              <td width="491"
                style="width: 491px; border: solid 1px #c0c0c0;"><p
                style="margin: 0px 0px 0px 13px;">Code de l'usinage de type
                <span style="color: #0000ff;">Simple</span> ou <span
                style="color: #0000ff;">Composé</span>.</p>
              </td>
            </tr>
            <tr valign="middle" align="left">
              <td width="113"
                style="width: 113px; border: solid 1px #c0c0c0;"><p
                style="text-align: center;"><span
                class="f_Variables">cadre</span></p>
              </td>
              <td width="491"
                style="width: 491px; border: solid 1px #c0c0c0;"><p
                style="margin: 0px 0px 0px 13px;">Les valeurs possibles sont:
                <span style="color: #0000ff;">Dormant</span>, <span
                style="color: #0000ff;">Ouvrant</span>, <span
                style="color: #0000ff;">Mauclair</span>, <span
                style="color: #0000ff;">RenfortOuvrant</span>, <span
                style="color: #0000ff;">RenfortDormant</span>, <span
                style="color: #0000ff;">RenfortMauclair</span>. </p>

                <p style="margin: 0px 0px 0px 13px;">L'usinage sera envoyé vers
                le profil correspondant à un de ces types. </p>

                <p style="margin: 0px 0px 0px 13px;">Veuillez noter que le type
                de profil (défini dans la <a href="profils.php">table des
                profils</a>) doit correspondre à l'une des catégories
                suivantes: <span style="font-weight: bold;">Profil
                principal</span>, <span
                style="font-weight: bold;">Renfort</span>, <span
                style="font-weight: bold;">Mauclair</span>, <span
                style="font-weight: bold;">Renfort</span> <span
                style="font-weight: bold;">mauclair</span>. </p>

                <p style="margin: 0px 0px 0px 13px;">La catégorie <span
                style="font-weight: bold;">Profil principal</span> correspond à
                <span style="color: #0000ff;">Dormant</span> ,<span
                style="color: #0000ff;">Ouvrant </span>et <span
                style="color: #0000ff;">Traverse</span>; </p>

                <p style="margin: 0px 0px 0px 13px;">La catégorie <span
                style="font-weight: bold;">Renfort</span> correspond à <span
                style="color: #0000ff;">RenfortDormant</span> et <span
                style="color: #0000ff;">RenfortMauclair</span>.</p>
              </td>
            </tr>
            <tr valign="middle" align="left">
              <td width="113"
                style="width: 113px; border: solid 1px #c0c0c0;"><p
                style="text-align: center;"><span
                style="font-size: 5pt; font-family: 'Courier New'; color: #0000ff;"></span><span
                class="f_Variables">bord</span></p>
              </td>
              <td width="491"
                style="width: 491px; border: solid 1px #c0c0c0;"><p
                style="margin: 0px 0px 0px 13px;">Bord du cadre vers lequel
                l'usinage doit être envoyé. Les valeurs possibles sont: <span
                style="color: #0000ff;">Haut</span>, <span
                style="color: #0000ff;">Bas</span>, <span
                style="color: #0000ff;">Gauche</span>, <span
                style="color: #0000ff;">Droite</span>.</p>

                <p style="margin: 0px 0px 0px 13px;">Vous pouvez aussi indiquer
                devant le bord le signe <span style="color: #0000ff;">-
                &gt;</span> (<span style="color: #0000ff;">- &gt;Haut</span>,
                <span style="color: #0000ff;">- &gt;Bas</span>, <span
                style="color: #0000ff;">- &gt;Gauche</span>, <span
                style="color: #0000ff;">- &gt;Droite</span>). Dans ce cas, le
                bord n'indique plus sur quel côté du cadre l'usinage doit
                arriver, mais plutôt la direction à partir duquel il faut
                rechercher la destination, compte tenu de la position d'origine
                de l'usinage (voyez le quatrième exemple).</p>
              </td>
            </tr>
            <tr valign="middle" align="left">
              <td width="113"
                style="width: 113px; border: solid 1px #c0c0c0;"><p
                style="text-align: center;"><span
                class="f_Variables">vantail</span></p>
              </td>
              <td width="491"
                style="width: 491px; border: solid 1px #c0c0c0;"><p
                style="margin: 0px 0px 0px 13px;">Numéro du vantail depuis ou
                sur lequel l'usinage est ou doit être envoyé (de 1 à n, en
                partant de la gauche ou du bas)</p>

                <p style="margin: 0px 0px 0px 13px;">Seuls les usinages venant
                du dormant sur le dormant, ou d'une traverse de dormant sur le
                dormant ne nécessite pas cette information.</p>
              </td>
            </tr>
            <tr valign="middle" align="left">
              <td width="113"
                style="width: 113px; border: solid 1px #c0c0c0;"><p
                style="text-align: center;"><span
                class="f_Variables">SPECIAL</span></p>
              </td>
              <td width="491"
                style="width: 491px; border: solid 1px #c0c0c0;"><p
                style="margin: 0px 0px 0px 13px;">Si ce paramètre est spécifié,
                l'usinage n'est pas envoyé vers un cadre spécifique (dormant,
                ouvrant, ...), mais plutôt vers un type de profil, dont la
                catégorie numérique correspond à celle du paramètre suivant le
                paramètre <span style="color: #0000ff;">SPECIAL</span>. Ceci
                permet d'envoyer des usinages vers tout type de profil, quelle
                que soit son appartenance (dormant, ouvrant, traverse, profil
                périphérique, croisillon, ...)</p>
              </td>
            </tr>
            <tr valign="middle" align="left">
              <td width="113"
                style="width: 113px; border: solid 1px #c0c0c0;"><p
                style="text-align: center;"><span
                class="f_Variables">categorie</span></p>
              </td>
              <td width="491"
                style="width: 491px; border: solid 1px #c0c0c0;"><p
                style="margin: 0px 0px 0px 13px;">Utilisé juste après le
                paramètre <span style="color: #0000ff;">SPECIAL</span>, ce
                paramètre indique la catégorie de profil sur lequel l'usinage
                doit être appliqué.</p>

                <p style="margin: 0px 0px 0px 13px;"><span
                style="font-weight: bold; text-decoration: underline;">Remarque</span>
                : si deux profils avec la même catégorie sont situés sur le
                même bord, les usinages seront envoyées uniquement sur le
                premier profil rencontré dans la direction spécifiée.</p>
              </td>
            </tr>
            <tr valign="middle" align="left">
              <td width="113"
                style="width: 113px; border: solid 1px #c0c0c0;"><p
                style="text-align: center;"><span
                class="f_Variables">AUTO</span></p>
              </td>
              <td width="491"
                style="width: 491px; border: solid 1px #c0c0c0;"><p
                style="margin: 0px 0px 0px 13px;">Si ce paramètre est spécifié,
                l'usinage est appliqué directement sur le profil auquel
                appartient la formule dans laquelle se trouve l'instruction
                d'usinage.</p>
              </td>
            </tr>
          </tbody>
        </table>
        </div>

        <p class="p_Interligne"><span class="f_Interligne"
        style="text-decoration: underline;"> </span></p>

        <p style="margin: 0px 0px 0px 24px;"><span
        style="text-decoration: underline;">Exemples d'utilisation:</span></p>

        <p style="margin: 0px 0px 0px 48px;">1. Dans une formule d'ouvrant ou
        de quincaillerie:</p>

        <p style="margin: 0px 0px 0px 62px;"><span class="f_Variables">#
        Usinage d'un trou de poignée sur le vantail 2 d'un double ouvrant
        droit</span></p>

        <p style="margin: 0px 0px 0px 62px;"><span class="f_Variables">Usinage
        (400, bas, simple, POIGNEE, ouvrant, gauche, 2)</span></p>

        <p style="margin: 0px 0px 0px 62px;"><span class="f_Variables">#
        Usinage de la charnière haut (simple ouvrant gauche)</span></p>

        <p style="margin: 0px 0px 0px 62px;"><span class="f_Variables">Usinage
        (80, haut, simple, CHARNIERE, dormant, gauche)</span></p>

        <p class="p_Interligne"><span class="f_Interligne"> </span></p>

        <p style="margin: 0px 0px 0px 48px;">2. Dans une formule de
        traverse:</p>

        <p style="margin: 0px 0px 0px 61px;"><span style="color: #0000ff;">#
        Usinage du trou de fixation d'une traverse verticale dans le
        dormant</span></p>

        <p style="margin: 0px 0px 0px 61px;"><span
        style="color: #0000ff;">Usinage (0, centre, simple, TRAVERSE, dormant,
        bas)</span></p>

        <p style="margin: 0px 0px 0px 61px;"><span
        style="color: #0000ff;">Usinage (0, centre, simple, TRAVERSE, dormant,
        haut)</span></p>

        <p style="margin: 0px 0px 0px 61px;"><span style="color: #0000ff;">#
        Usinage des trous d'évacuation sur une traverse horizontale</span></p>

        <p style="margin: 0px 0px 0px 61px;"><span
        style="color: #0000ff;">Usinage (100, gauche, simple, EVAC,
        auto)</span></p>

        <p style="margin: 0px 0px 0px 61px;"><span
        style="color: #0000ff;">Usinage (100, droite, simple, EVAC,
        auto)</span></p>

        <p style="margin: 0px 0px 0px 61px;"><span style="color: #0000ff;">#
        usinage d'un trou d'évacuation, avec un deuxième paramètre numérique
        associé</span></p>

        <p style="margin: 0px 0px 0px 61px;"><span style="color: #0000ff;">pos
        : 2</span></p>

        <p style="margin: 0px 0px 0px 61px;"><span style="color: #0000ff;">org
        : 2</span></p>

        <p style="margin: 0px 0px 0px 61px;"><span
        style="color: #0000ff;">pos[1] := 100</span></p>

        <p style="margin: 0px 0px 0px 61px;"><span
        style="color: #0000ff;">pos[2] := 1</span></p>

        <p style="margin: 0px 0px 0px 61px;"><span
        style="color: #0000ff;">org[1] := gauche</span></p>

        <p style="margin: 0px 0px 0px 61px;"><span
        style="color: #0000ff;">org[2] := absolu</span></p>

        <p style="margin: 0px 0px 0px 61px;"><span
        style="color: #0000ff;">UsinageExt (pos, org, EVAC, auto)</span></p>

        <p class="p_Interligne"><span class="f_Interligne"> </span></p>

        <p style="margin: 0px 0px 0px 48px;">3. Usinage depuis le dormant vers
        un profil périphérique de catégorie 100:</p>

        <p style="margin: 0px 0px 0px 62px;"><span
        style="color: #0000ff;">Usinage (400, bas, simple, MACONNERIE, special,
        100, bord)</span></p>

        <p class="p_Interligne"><span class="f_Interligne"> </span></p>

        <p style="margin: 0px 0px 0px 48px;">4. Usinage depuis un profil
        périphérique à droite vers le dormant droit (de catégorie 110):</p>

        <p style="margin: 0px 0px 0px 62px;"><span
        style="color: #0000ff;">Usinage (400, bas, simple, MACONNERIE, special,
        110, -&gt;gauche)</span></p>

        <p style="margin: 0px 0px 0px 48px;"><span
        style="font-size: 11pt; font-family: 'Courier New'; color: #0000ff;"> </span></p>

        <p> </p>
      </td>
    </tr>
  </tbody>
</table>
</div>
</body>
</html>
